### ISSUE TITLE
how do I add article?

### ISSUE THREAD

**Issue by vorcigernix** [kendallstrautman/brevifolia-next-tinacms#10]
I am digging through the code and it is not clear to me how can I add a new blog article. It works if I add an md file manually, but that's not what you expect from content creators.

**Comment by kendallstrautman** [comment]
Hi @vorcigernix, you'd need to add a `content-creator` plugin to the blog! Here is a [blog](https://tinacms.org/blog/add-and-delete-files) on how to do that. Feel free to fork and make a PR to this repo if you want to add it to the demo.
