### ISSUE TITLE
Running the application gives error

### ISSUE THREAD

**Issue by Maniraj-Murugan** [kendallstrautman/brevifolia-next-tinacms#14]
I have cloned this application and done `npm install` and then run the application through the command `npm run dev` and when I visit the url `localhost:3000 `then it gives the following error.

**Unhandled Runtime Error
Error: useCMS could not find an instance of CMS**

![squidex-custom-editor-tinymce](https://user-images.githubusercontent.com/47934659/86886514-b5185980-c114-11ea-82e4-b585fb4dcaf5.png)

**Comment by kendallstrautman** [comment]
Hey @Maniraj-Murugan, sorry for the delay. This is a dependency issue, my guess would be multiple versions of `tinacms` would be installed. I've updated all the Tina packages in [this PR](https://github.com/kendallstrautman/brevifolia-next-tinacms/pull/17), that should fix your problem. Make sure to remove `node_modules` and possibly `yarn.lock` before you reinstall with the upgraded packages.
